use supplychain;
select * from supplychain_data;

Describe supplychain_data;

-- 1.Total Revenue by Product Type:
-- Calculate the total revenue generated by each product type. This can help identify the most profitable products

select Product_type, round(sum(Revenue_generated),2) from supplychain_data group by Product_type;

-- 2. Shipping Costs by Carrier
-- Calculating the average shipping costs for each shipping carrier to evaluate which carrier is the most cost-effective

select Shipping_carriers, round(avg(Shipping_costs),2) as Average_Cost from supply_chain_data_1 group by Shipping_carriers;

-- 3. Lead Times by Supplier:
-- Average lead times for each supplier to assess their reliability in delivering products on time

select * from supplychain_data;
select Supplier_name, avg(Lead_time) as Avg_Leadtime from supplychain_data group by Supplier_name;

-- 4. Total Products Sold by Location:
-- Determining the total number of products sold in each location to understand regional demand

select Location, sum(Number_of_products_sold) as Product_sold from supplychain_data group by Location order by Product_sold desc;

-- 5.Defect Rates by Inspection Results:
-- Calculate the defect rates for different inspection results to assess product quality

select Inspection_results, round(avg(Defect_rates), 2) defective_rate from supplychain_data group by Inspection_results;
                                        
-- 6. Ranking Products by Profitability:
-- Write a query to rank products based on profitability, where profitability is calculated as (Revenue generated - Manufacturing costs - Shipping costs)

select SKU, Product_type, ("Revenue_generated" - "Manufacturing_costs" - "Shipping_costs") as Profitability, 
dense_rank() over(partition by  Product_type order by "Revenue_generated", "Manufacturing_costs", "Shipping_costs" Desc) 
as Profitability_Rank from supplychain_data;

-- 7. Supplier Performance Analysis:
-- Calculate the average lead time for each supplier and identify suppliers with lead times higher than the overall average

select Supplier_name, avg(Lead_times) as Avg_lead_time from supplychain_data
group by Supplier_name;

-- 8. Top 5 Shipping Carriers by Cost Efficiency:
-- Determine the top 5 shipping carriers with the lowest average shipping costs per product shipped

select Product_type, Shipping_carriers, avg(Shipping_costs) as avg_shippingcost, 
dense_rank() over(partition by Product_type order by avg(Shipping_costs)) as drank
from supplychain_data
group by Shipping_carriers, Product_type;

